version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/app-code

hooks:
  BeforeInstall:
    - location: scripts/clean_app_folder.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
    - location: scripts/start_container.sh
      timeout: 300
      runas: root
